version: "3.1"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    env_file: source/config/db.env
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge